#!/bin/sh

if [ -n "$GO_PIPELINE_LABEL" ] ; then
    buildVersion=$GO_PIPELINE_LABEL
else
    buildVersion='LOCAL'
fi

mkdir -p target
zip -rq target/casper-cass-$buildVersion.zip modules scripts steps
